# Generated by Django 4.2.7 on 2025-12-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='second_last_name',
            field=models.CharField(default='Pendiente', max_length=150),
        ),
    ]
