# Generated by Django 4.2.7 on 2025-12-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_multiple_files_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
