# Generated by Django 4.2.7 on 2025-12-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_lesson_youtube_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plin_qr',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='yape_qr',
            field=models.URLField(blank=True, null=True),
        ),
    ]
