# Generated by Django 4.2.7 on 2025-12-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_plin_qr_user_yape_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='plin_qr',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='yape_qr',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
