# Generated by Django 4.2.7 on 2025-12-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_avatar_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherpayment',
            name='voucher_image',
            field=models.URLField(max_length=500),
        ),
    ]
