# Generated by Django 4.2.7 on 2025-12-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_voucherpayment_voucher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherpayment',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
